name: terminal-fun
base: core24
version: git
summary: Master the Linux command line through interactive lessons
description: |
  Terminal Fun is an interactive, graphical learning application that makes mastering
  the Linux command line enjoyable and accessible. Whether you're a complete beginner
  who's never opened a terminal or an experienced user looking to fill in knowledge
  gaps, Terminal Fun provides a structured, hands-on learning experience.

  **What You'll Learn**

  Terminal Fun covers essential command-line skills through 23 comprehensive lessons
  organized into 9 progressive categories:

  • Introduction - Get comfortable with the terminal interface
  • Shell Basics - Master environment variables, command history, and aliases
  • Navigation - Learn to move efficiently through the filesystem
  • File Operations - Create, modify, find, and manage files with confidence
  • Text Editors - Master Vim for powerful terminal-based text editing
  • Pipes & Redirection - Compose powerful command pipelines
  • Process Management - Monitor and control running programs
  • System Administration - Use sudo, apt, and snap like a pro
  • Version Control - Learn Git from basics to advanced topics

  **Interactive Learning Experience**

  The app features a unique split-screen interface with lesson content on the left
  and a live, embedded terminal on the right. As you read through clear explanations
  and practical examples, you can immediately try commands in the integrated terminal.
  Each lesson includes multiple hands-on exercises that build your muscle memory and
  confidence.

  Track your progress as you complete lessons - checkmarks appear next to finished
  topics so you always know where you are in your learning journey. The lessons are
  designed to build on each other, starting with absolute basics and progressing to
  advanced topics like file permissions, Vim text editing, process priority, package
  management, and Git version control.

  **Safe Learning Environment**

  Terminal Fun creates an isolated virtual home directory where you can experiment
  freely without affecting your real files. The environment comes pre-configured with
  a professional .vimrc (syntax highlighting for 9+ languages) and .gitconfig (colors
  and helpful aliases), giving you a production-quality setup from day one.

  **Key Features**

  • 23 comprehensive lessons covering fundamental to advanced topics
  • Split-screen interface: lessons + live terminal side-by-side
  • Hands-on exercises with practical, real-world examples
  • Visual progress tracking with checkmark completion indicators
  • Embedded VTE terminal with Ubuntu theme for immediate practice
  • Isolated virtual environment for risk-free experimentation
  • Pre-configured Vim and Git for professional workflows
  • Beautiful GNOME/Adwaita interface that feels native
  • Keyboard shortcuts: Ctrl+Shift+C to copy, Ctrl+Shift+V to paste
  • Self-paced learning - go at your own speed
  • All content works offline - no internet required

  **Who Is This For?**

  • Beginners who want to learn the command line from scratch
  • Linux users transitioning from GUI-only workflows
  • Students learning system administration
  • Developers who need stronger command-line skills
  • Anyone who wants to understand what those terminal commands actually do

  **Why Terminal Fun?**

  Most command-line tutorials are either too dry (man pages) or too scattered (random
  blog posts). Terminal Fun provides a structured, engaging curriculum with immediate
  feedback. The integrated terminal means you're always one click away from trying
  what you just learned. No context switching, no copy-pasting - just pure learning.

  By the time you complete all lessons, you'll be comfortable navigating filesystems,
  editing files with Vim, composing command pipelines, managing processes, performing
  system administration tasks, and tracking code with Git. You'll understand not just
  how to use commands, but why they work the way they do and when to use them.

  Terminal Fun turns command-line anxiety into command-line confidence!

title: Terminal Fun
license: GPL-3.0
contact: https://github.com/kenvandine/terminal-fun/issues
issues: https://github.com/kenvandine/terminal-fun/issues
source-code: https://github.com/kenvandine/terminal-fun

grade: stable
confinement: strict

apps:
  terminal-fun:
    command: bin/terminal-fun
    desktop: meta/gui/terminal-fun.desktop
    extensions: [gnome]
    plugs:
      - process-control
      - mount-observe
      - browser-support
      - system-observe
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12/site-packages
      TERMINAL_FUN_LESSONS_DIR: $SNAP/lessons
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH

parts:
  terminal-fun:
    plugin: python
    source: .
    python-packages:
      - PyYAML>=6.0
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - gir1.2-vte-3.91
      - gir1.2-pango-1.0
      - libvte-2.91-0
      - libvte-2.91-common
    override-build: |
      craftctl default

      # Install the main application
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp main.py $CRAFT_PART_INSTALL/bin/terminal-fun
      cp lesson_loader.py $CRAFT_PART_INSTALL/bin/
      cp progress_tracker.py $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/terminal-fun

      # Install lessons
      mkdir -p $CRAFT_PART_INSTALL/lessons
      cp -r lessons/* $CRAFT_PART_INSTALL/lessons/

      # Install sandbox for mock privileged commands
      mkdir -p $CRAFT_PART_INSTALL/sandbox/bin
      mkdir -p $CRAFT_PART_INSTALL/sandbox/lib
      cp sandbox/bin/* $CRAFT_PART_INSTALL/sandbox/bin/
      cp sandbox/lib/* $CRAFT_PART_INSTALL/sandbox/lib/
      chmod +x $CRAFT_PART_INSTALL/sandbox/bin/*

      # Install desktop file and icon
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp terminal-fun.desktop $CRAFT_PART_INSTALL/meta/gui/
      cp terminal-fun.png $CRAFT_PART_INSTALL/meta/gui/

  tools:
    plugin: nil
    stage-packages:
      - git
      - vim-nox
      - vim-runtime
      - bubblewrap
    organize:
      usr/bin/vim.nox: usr/bin/vim

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0
  /usr/share/vim:
    bind: $SNAP/usr/share/vim
  /usr/lib/git-core:
    bind: $SNAP/usr/lib/git-core
  /usr/share/git-core:
    bind: $SNAP/usr/share/git-core
